use std::{error::Error, ffi::CStr, fmt::Display};

use crate::{
    inners::{FromInner, IntoInner},
    uv::{self, uv_err_name, uv_errno_t, uv_strerror},
};

// type

#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Errno {
    E2BIG,
    EACCES,
    EADDRINUSE,
    EADDRNOTAVAIL,
    EAFNOSUPPORT,
    EAGAIN,
    EAI_ADDRFAMILY,
    EAI_AGAIN,
    EAI_BADFLAGS,
    EAI_BADHINTS,
    EAI_CANCELED,
    EAI_FAIL,
    EAI_FAMILY,
    EAI_MEMORY,
    EAI_NODATA,
    EAI_NONAME,
    EAI_OVERFLOW,
    EAI_PROTOCOL,
    EAI_SERVICE,
    EAI_SOCKTYPE,
    EALREADY,
    EBADF,
    EBUSY,
    ECANCELED,
    ECHARSET,
    ECONNABORTED,
    ECONNREFUSED,
    ECONNRESET,
    EDESTADDRREQ,
    EEXIST,
    EFAULT,
    EFBIG,
    EHOSTUNREACH,
    EINTR,
    EINVAL,
    EIO,
    EISCONN,
    EISDIR,
    ELOOP,
    EMFILE,
    EMSGSIZE,
    ENAMETOOLONG,
    ENETDOWN,
    ENETUNREACH,
    ENFILE,
    ENOBUFS,
    ENODEV,
    ENOENT,
    ENOMEM,
    ENONET,
    ENOPROTOOPT,
    ENOSPC,
    ENOSYS,
    ENOTCONN,
    ENOTDIR,
    ENOTEMPTY,
    ENOTSOCK,
    ENOTSUP,
    EOVERFLOW,
    EPERM,
    EPIPE,
    EPROTO,
    EPROTONOSUPPORT,
    EPROTOTYPE,
    ERANGE,
    EROFS,
    ESHUTDOWN,
    ESPIPE,
    ESRCH,
    ETIMEDOUT,
    ETXTBSY,
    EXDEV,
    UNKNOWN,
    EOF,
    ENXIO,
    EMLINK,
    EHOSTDOWN,
    EREMOTEIO,
    ENOTTY,
    EFTYPE,
    EILSEQ,
    ESOCKTNOSUPPORT,
    ENODATA,
    EUNATCH,
    ERRNO_MAX,
}

// impl

impl Errno {
    fn name(&self) -> String {
        unsafe { CStr::from_ptr(uv_err_name(self.into_inner())) }
            .to_string_lossy()
            .into_owned()
    }

    pub fn message(&self) -> String {
        unsafe { CStr::from_ptr(uv_strerror(self.into_inner())) }
            .to_string_lossy()
            .into_owned()
    }
}

// trait

impl Display for Errno {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.name(), self.message())
    }
}

impl Error for Errno {}

// inner

impl FromInner<uv_errno_t> for Errno {
    fn from_inner(value: uv_errno_t) -> Self {
        match value {
            uv::uv_errno_t_UV_E2BIG => Errno::E2BIG,
            uv::uv_errno_t_UV_EACCES => Errno::EACCES,
            uv::uv_errno_t_UV_EADDRINUSE => Errno::EADDRINUSE,
            uv::uv_errno_t_UV_EADDRNOTAVAIL => Errno::EADDRNOTAVAIL,
            uv::uv_errno_t_UV_EAFNOSUPPORT => Errno::EAFNOSUPPORT,
            uv::uv_errno_t_UV_EAGAIN => Errno::EAGAIN,
            uv::uv_errno_t_UV_EAI_ADDRFAMILY => Errno::EAI_ADDRFAMILY,
            uv::uv_errno_t_UV_EAI_AGAIN => Errno::EAI_AGAIN,
            uv::uv_errno_t_UV_EAI_BADFLAGS => Errno::EAI_BADFLAGS,
            uv::uv_errno_t_UV_EAI_BADHINTS => Errno::EAI_BADHINTS,
            uv::uv_errno_t_UV_EAI_CANCELED => Errno::EAI_CANCELED,
            uv::uv_errno_t_UV_EAI_FAIL => Errno::EAI_FAIL,
            uv::uv_errno_t_UV_EAI_FAMILY => Errno::EAI_FAMILY,
            uv::uv_errno_t_UV_EAI_MEMORY => Errno::EAI_MEMORY,
            uv::uv_errno_t_UV_EAI_NODATA => Errno::EAI_NODATA,
            uv::uv_errno_t_UV_EAI_NONAME => Errno::EAI_NONAME,
            uv::uv_errno_t_UV_EAI_OVERFLOW => Errno::EAI_OVERFLOW,
            uv::uv_errno_t_UV_EAI_PROTOCOL => Errno::EAI_PROTOCOL,
            uv::uv_errno_t_UV_EAI_SERVICE => Errno::EAI_SERVICE,
            uv::uv_errno_t_UV_EAI_SOCKTYPE => Errno::EAI_SOCKTYPE,
            uv::uv_errno_t_UV_EALREADY => Errno::EALREADY,
            uv::uv_errno_t_UV_EBADF => Errno::EBADF,
            uv::uv_errno_t_UV_EBUSY => Errno::EBUSY,
            uv::uv_errno_t_UV_ECANCELED => Errno::ECANCELED,
            uv::uv_errno_t_UV_ECHARSET => Errno::ECHARSET,
            uv::uv_errno_t_UV_ECONNABORTED => Errno::ECONNABORTED,
            uv::uv_errno_t_UV_ECONNREFUSED => Errno::ECONNREFUSED,
            uv::uv_errno_t_UV_ECONNRESET => Errno::ECONNRESET,
            uv::uv_errno_t_UV_EDESTADDRREQ => Errno::EDESTADDRREQ,
            uv::uv_errno_t_UV_EEXIST => Errno::EEXIST,
            uv::uv_errno_t_UV_EFAULT => Errno::EFAULT,
            uv::uv_errno_t_UV_EFBIG => Errno::EFBIG,
            uv::uv_errno_t_UV_EHOSTUNREACH => Errno::EHOSTUNREACH,
            uv::uv_errno_t_UV_EINTR => Errno::EINTR,
            uv::uv_errno_t_UV_EINVAL => Errno::EINVAL,
            uv::uv_errno_t_UV_EIO => Errno::EIO,
            uv::uv_errno_t_UV_EISCONN => Errno::EISCONN,
            uv::uv_errno_t_UV_EISDIR => Errno::EISDIR,
            uv::uv_errno_t_UV_ELOOP => Errno::ELOOP,
            uv::uv_errno_t_UV_EMFILE => Errno::EMFILE,
            uv::uv_errno_t_UV_EMSGSIZE => Errno::EMSGSIZE,
            uv::uv_errno_t_UV_ENAMETOOLONG => Errno::ENAMETOOLONG,
            uv::uv_errno_t_UV_ENETDOWN => Errno::ENETDOWN,
            uv::uv_errno_t_UV_ENETUNREACH => Errno::ENETUNREACH,
            uv::uv_errno_t_UV_ENFILE => Errno::ENFILE,
            uv::uv_errno_t_UV_ENOBUFS => Errno::ENOBUFS,
            uv::uv_errno_t_UV_ENODEV => Errno::ENODEV,
            uv::uv_errno_t_UV_ENOENT => Errno::ENOENT,
            uv::uv_errno_t_UV_ENOMEM => Errno::ENOMEM,
            uv::uv_errno_t_UV_ENONET => Errno::ENONET,
            uv::uv_errno_t_UV_ENOPROTOOPT => Errno::ENOPROTOOPT,
            uv::uv_errno_t_UV_ENOSPC => Errno::ENOSPC,
            uv::uv_errno_t_UV_ENOSYS => Errno::ENOSYS,
            uv::uv_errno_t_UV_ENOTCONN => Errno::ENOTCONN,
            uv::uv_errno_t_UV_ENOTDIR => Errno::ENOTDIR,
            uv::uv_errno_t_UV_ENOTEMPTY => Errno::ENOTEMPTY,
            uv::uv_errno_t_UV_ENOTSOCK => Errno::ENOTSOCK,
            uv::uv_errno_t_UV_ENOTSUP => Errno::ENOTSUP,
            uv::uv_errno_t_UV_EOVERFLOW => Errno::EOVERFLOW,
            uv::uv_errno_t_UV_EPERM => Errno::EPERM,
            uv::uv_errno_t_UV_EPIPE => Errno::EPIPE,
            uv::uv_errno_t_UV_EPROTO => Errno::EPROTO,
            uv::uv_errno_t_UV_EPROTONOSUPPORT => Errno::EPROTONOSUPPORT,
            uv::uv_errno_t_UV_EPROTOTYPE => Errno::EPROTOTYPE,
            uv::uv_errno_t_UV_ERANGE => Errno::ERANGE,
            uv::uv_errno_t_UV_EROFS => Errno::EROFS,
            uv::uv_errno_t_UV_ESHUTDOWN => Errno::ESHUTDOWN,
            uv::uv_errno_t_UV_ESPIPE => Errno::ESPIPE,
            uv::uv_errno_t_UV_ESRCH => Errno::ESRCH,
            uv::uv_errno_t_UV_ETIMEDOUT => Errno::ETIMEDOUT,
            uv::uv_errno_t_UV_ETXTBSY => Errno::ETXTBSY,
            uv::uv_errno_t_UV_EXDEV => Errno::EXDEV,
            uv::uv_errno_t_UV_UNKNOWN => Errno::UNKNOWN,
            uv::uv_errno_t_UV_EOF => Errno::EOF,
            uv::uv_errno_t_UV_ENXIO => Errno::ENXIO,
            uv::uv_errno_t_UV_EMLINK => Errno::EMLINK,
            uv::uv_errno_t_UV_EHOSTDOWN => Errno::EHOSTDOWN,
            uv::uv_errno_t_UV_EREMOTEIO => Errno::EREMOTEIO,
            uv::uv_errno_t_UV_ENOTTY => Errno::ENOTTY,
            uv::uv_errno_t_UV_EFTYPE => Errno::EFTYPE,
            uv::uv_errno_t_UV_EILSEQ => Errno::EILSEQ,
            uv::uv_errno_t_UV_ESOCKTNOSUPPORT => Errno::ESOCKTNOSUPPORT,
            uv::uv_errno_t_UV_ENODATA => Errno::ENODATA,
            uv::uv_errno_t_UV_EUNATCH => Errno::EUNATCH,
            uv::uv_errno_t_UV_ERRNO_MAX => Errno::ERRNO_MAX,
            _ => unreachable!(),
        }
    }
}

impl IntoInner<uv_errno_t> for Errno {
    fn into_inner(self) -> uv_errno_t {
        match self {
            Errno::E2BIG => uv::uv_errno_t_UV_E2BIG,
            Errno::EACCES => uv::uv_errno_t_UV_EACCES,
            Errno::EADDRINUSE => uv::uv_errno_t_UV_EADDRINUSE,
            Errno::EADDRNOTAVAIL => uv::uv_errno_t_UV_EADDRNOTAVAIL,
            Errno::EAFNOSUPPORT => uv::uv_errno_t_UV_EAFNOSUPPORT,
            Errno::EAGAIN => uv::uv_errno_t_UV_EAGAIN,
            Errno::EAI_ADDRFAMILY => uv::uv_errno_t_UV_EAI_ADDRFAMILY,
            Errno::EAI_AGAIN => uv::uv_errno_t_UV_EAI_AGAIN,
            Errno::EAI_BADFLAGS => uv::uv_errno_t_UV_EAI_BADFLAGS,
            Errno::EAI_BADHINTS => uv::uv_errno_t_UV_EAI_BADHINTS,
            Errno::EAI_CANCELED => uv::uv_errno_t_UV_EAI_CANCELED,
            Errno::EAI_FAIL => uv::uv_errno_t_UV_EAI_FAIL,
            Errno::EAI_FAMILY => uv::uv_errno_t_UV_EAI_FAMILY,
            Errno::EAI_MEMORY => uv::uv_errno_t_UV_EAI_MEMORY,
            Errno::EAI_NODATA => uv::uv_errno_t_UV_EAI_NODATA,
            Errno::EAI_NONAME => uv::uv_errno_t_UV_EAI_NONAME,
            Errno::EAI_OVERFLOW => uv::uv_errno_t_UV_EAI_OVERFLOW,
            Errno::EAI_PROTOCOL => uv::uv_errno_t_UV_EAI_PROTOCOL,
            Errno::EAI_SERVICE => uv::uv_errno_t_UV_EAI_SERVICE,
            Errno::EAI_SOCKTYPE => uv::uv_errno_t_UV_EAI_SOCKTYPE,
            Errno::EALREADY => uv::uv_errno_t_UV_EALREADY,
            Errno::EBADF => uv::uv_errno_t_UV_EBADF,
            Errno::EBUSY => uv::uv_errno_t_UV_EBUSY,
            Errno::ECANCELED => uv::uv_errno_t_UV_ECANCELED,
            Errno::ECHARSET => uv::uv_errno_t_UV_ECHARSET,
            Errno::ECONNABORTED => uv::uv_errno_t_UV_ECONNABORTED,
            Errno::ECONNREFUSED => uv::uv_errno_t_UV_ECONNREFUSED,
            Errno::ECONNRESET => uv::uv_errno_t_UV_ECONNRESET,
            Errno::EDESTADDRREQ => uv::uv_errno_t_UV_EDESTADDRREQ,
            Errno::EEXIST => uv::uv_errno_t_UV_EEXIST,
            Errno::EFAULT => uv::uv_errno_t_UV_EFAULT,
            Errno::EFBIG => uv::uv_errno_t_UV_EFBIG,
            Errno::EHOSTUNREACH => uv::uv_errno_t_UV_EHOSTUNREACH,
            Errno::EINTR => uv::uv_errno_t_UV_EINTR,
            Errno::EINVAL => uv::uv_errno_t_UV_EINVAL,
            Errno::EIO => uv::uv_errno_t_UV_EIO,
            Errno::EISCONN => uv::uv_errno_t_UV_EISCONN,
            Errno::EISDIR => uv::uv_errno_t_UV_EISDIR,
            Errno::ELOOP => uv::uv_errno_t_UV_ELOOP,
            Errno::EMFILE => uv::uv_errno_t_UV_EMFILE,
            Errno::EMSGSIZE => uv::uv_errno_t_UV_EMSGSIZE,
            Errno::ENAMETOOLONG => uv::uv_errno_t_UV_ENAMETOOLONG,
            Errno::ENETDOWN => uv::uv_errno_t_UV_ENETDOWN,
            Errno::ENETUNREACH => uv::uv_errno_t_UV_ENETUNREACH,
            Errno::ENFILE => uv::uv_errno_t_UV_ENFILE,
            Errno::ENOBUFS => uv::uv_errno_t_UV_ENOBUFS,
            Errno::ENODEV => uv::uv_errno_t_UV_ENODEV,
            Errno::ENOENT => uv::uv_errno_t_UV_ENOENT,
            Errno::ENOMEM => uv::uv_errno_t_UV_ENOMEM,
            Errno::ENONET => uv::uv_errno_t_UV_ENONET,
            Errno::ENOPROTOOPT => uv::uv_errno_t_UV_ENOPROTOOPT,
            Errno::ENOSPC => uv::uv_errno_t_UV_ENOSPC,
            Errno::ENOSYS => uv::uv_errno_t_UV_ENOSYS,
            Errno::ENOTCONN => uv::uv_errno_t_UV_ENOTCONN,
            Errno::ENOTDIR => uv::uv_errno_t_UV_ENOTDIR,
            Errno::ENOTEMPTY => uv::uv_errno_t_UV_ENOTEMPTY,
            Errno::ENOTSOCK => uv::uv_errno_t_UV_ENOTSOCK,
            Errno::ENOTSUP => uv::uv_errno_t_UV_ENOTSUP,
            Errno::EOVERFLOW => uv::uv_errno_t_UV_EOVERFLOW,
            Errno::EPERM => uv::uv_errno_t_UV_EPERM,
            Errno::EPIPE => uv::uv_errno_t_UV_EPIPE,
            Errno::EPROTO => uv::uv_errno_t_UV_EPROTO,
            Errno::EPROTONOSUPPORT => uv::uv_errno_t_UV_EPROTONOSUPPORT,
            Errno::EPROTOTYPE => uv::uv_errno_t_UV_EPROTOTYPE,
            Errno::ERANGE => uv::uv_errno_t_UV_ERANGE,
            Errno::EROFS => uv::uv_errno_t_UV_EROFS,
            Errno::ESHUTDOWN => uv::uv_errno_t_UV_ESHUTDOWN,
            Errno::ESPIPE => uv::uv_errno_t_UV_ESPIPE,
            Errno::ESRCH => uv::uv_errno_t_UV_ESRCH,
            Errno::ETIMEDOUT => uv::uv_errno_t_UV_ETIMEDOUT,
            Errno::ETXTBSY => uv::uv_errno_t_UV_ETXTBSY,
            Errno::EXDEV => uv::uv_errno_t_UV_EXDEV,
            Errno::UNKNOWN => uv::uv_errno_t_UV_UNKNOWN,
            Errno::EOF => uv::uv_errno_t_UV_EOF,
            Errno::ENXIO => uv::uv_errno_t_UV_ENXIO,
            Errno::EMLINK => uv::uv_errno_t_UV_EMLINK,
            Errno::EHOSTDOWN => uv::uv_errno_t_UV_EHOSTDOWN,
            Errno::EREMOTEIO => uv::uv_errno_t_UV_EREMOTEIO,
            Errno::ENOTTY => uv::uv_errno_t_UV_ENOTTY,
            Errno::EFTYPE => uv::uv_errno_t_UV_EFTYPE,
            Errno::EILSEQ => uv::uv_errno_t_UV_EILSEQ,
            Errno::ESOCKTNOSUPPORT => uv::uv_errno_t_UV_ESOCKTNOSUPPORT,
            Errno::ENODATA => uv::uv_errno_t_UV_ENODATA,
            Errno::EUNATCH => uv::uv_errno_t_UV_EUNATCH,
            Errno::ERRNO_MAX => uv::uv_errno_t_UV_ERRNO_MAX,
        }
    }
}
